RonRadtke/react-native-blob-util

- README.md
- android/src/main/AndroidManifest.xml
- package.json
Still need to adjust the rights so external storage is only used for api < 28
> Fix some permissons and the readme to specify a config

- windows/RNFetchBlob/RNFetchBlob.cpp
- windows/RNFetchBlob/RNFetchBlob.h
> Updated ProcessRequestAsync

- README.md
NIce project there :)
I just changed Andorid to Android
> Fix a Typo in Android title in Readme

- android/src/main/java/com/ReactNativeBlobUtil/Utils/Tls12SocketFactory.java
Resolves https://github.com/RonRadtke/react-native-blob-util/issues/41
> Remove / modify problematic javadoc comment syntax

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
Fix a problem where react-native-blob-util tries to encode the response body as utf-8 rather than decode it as utf-8 to determine if it is valid utf-8.
> Android response encode/decode issue

- README.md
^ 😄 Good luck with the project!
> Update Readme.md to fix small typos

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java
- index.d.ts
> Fix actionViewIntent open file intent with Android 11+ devices

- class/ReactNativeBlobUtilBlobResponse.js
> added missing base64 dependency

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilBody.java
A fix for an issue I submitted: https://github.com/RonRadtke/react-native-blob-util/issues/137
This change refactors the logic to initialize the input stream used send response data to okhttp into a method so that the input stream may be initialized and used multiple times by okhttp.
> A fix for "unexpected end of stream error" issue #137

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
Currently progress is not reported when downloads are set to use Android's DownloadManager, and this appears to be an issue that's been in this library since the previous fork.  I've taken changes from another patch aimed at the previous fork and adapted them for this version: https://github.com/joltup/rn-fetch-blob/issues/697#issuecomment-945084417
My Java experience is pretty shallow but from my limited testing it seems to work.
> Enable reporting of progress from Android DownloadManager

- README.md
> README: fix wrong link

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
> Fix bug issue #113 in new version package(0.16.3)

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
The new updates have a bug again [#179 ](https://github.com/RonRadtke/react-native-blob-util/issues/179)
> Fix bug Illegal callback invocation from native module

- index.d.ts
> Correct the return type of openDocument

- react-native-blob-util.podspec
Issue: https://github.com/RonRadtke/react-native-blob-util/issues/284
> Fix `pod install` for old version of react native with new arch

- ios/ReactNativeBlobUtilRequest.mm
If a download is determined to be using [chunked transfer encoding][1] (through [`NSURLResponse.expectedContentLength`][2] returning [`NSURLResponseUnknownLength`][3]), replicate the behaviour in the Android native component of the plugin; reporting:
* (0,-1) for each intermediate progress event, and
* (total,total) for the final progress event
[1]: https://datatracker.ietf.org/doc/html/rfc9112#section-7.1
[2]: https://developer.apple.com/documentation/foundation/nsurlresponse/1413507-expectedcontentlength
[3]: https://developer.apple.com/documentation/foundation/nsurlresponseunknownlength
> feat(ios): replicate Android chunked download reporting

- android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java
Fixes https://github.com/RonRadtke/react-native-blob-util/issues/180
> prevent returning dirty buffer when reading stream

- class/ReactNativeBlobUtilSession.js
Related to [#393](https://github.com/RonRadtke/react-native-blob-util/issues/393)
I spent some time trying to setup jest, but can't get it to work properly. Is it ok to make PR without tests?
> fix(Session): remove() method doesn't remove path from list

- README.md
Record the problems you encounter
> Update usage document

- README.md
- examples/ReactNativeBlobUtil/package.json
- package.json
- yarn.lock
Upgrade react-native and react-native-windows
yarn upgrade react-native@^0.78.2
yarn upgrade react-native-windows@^0.78.2
yarn upgrade react@^19.0.0
Example app works fine:
> Upgrade RN and RNW to 0.78
