android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java

A previous change to rn-fetch-blob's mv implementation entailed copying the source file to the destination file and then deleting the source file.  This approach has an undesirable impact on the mv operation, where the operation takes orders of magnitude longer to complete.  It also adds disk space requirements that shouldn't be necessary, since both files need to exist at the same time.
This change goes back to using the renameTo() method, while adding some extra error checking to hopefully alleviate whatever problems caused the original fix.
Note that the POSIX mv() and rename() methods both stipulate that moving to a non-existent directory should be treated as an error.

Change Android mv() back to using the system renameTo() method.

---

ios/ReactNativeBlobUtilFS.m

As documented in https://developer.apple.com/documentation/foundation/nsdata/1408033-writetofile, `writeToFile` may return NO if it failed for some reason (e.g., invalid path or not enough space).
Right now, the code is not handling this scenario and the file is reported back as written, even if it fails.
This PR adds a check to make sure the file is properly written.
PS: It would be great for this package to stop being a fork since I end up in the old package every time I want to do a PR!
@RonRadtke We have been seeing some data loss very rarely, but this is most likely the cause we have found. Please review and merge asap!

check write results to handle failures

---

android/build.gradle

Fixes Gradle 7 deprecations with the Android build.gradle file.
- Upgrades to the maven-publish plugin
- Resolves build issues with Javadoc plugin
I validated that both ./gradlew build and ./gradlew publish were successful. Javadoc is now being generated successfully.

Fix Gradle 7 deprecations

---

fetch.js

fetch.js - call fs.session() instead of session(). Fixes ReferenceError session is not defined.

fetch.js - call fs.session() instead of session().

---

android/build.gradle

The `afterEvaluate` section in `build.gradle` breaks the RN building from source. ( I'm testing RN 0.67 )
Throws:
```
* What went wrong:
A problem occurred configuring project ':react-native-blob-util'.
> Could not resolve all files for configuration ':react-native-blob-util:debugCompileClasspath'.
> Could not resolve com.facebook.react:react-native:+.
Required by:
project :react-native-blob-util
> No matching configuration of project :ReactAndroid was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' but:
- None of the consumable configurations have attributes.
```
Seems the `afterEvaluate` in `build.gradle` is only needed when build/publish this lib alone, this PR add a check to …

android: only do gradle afterEvaluate when building this lib alone

---

ios/ReactNativeBlobUtilReqBuilder.m

Fix ios/RNFetchBlobReqBuilder.m - buildOctetRequest method upload file failed with url prefix "file://".

fix upload file failed with url prefix "file://"

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java

Resubmitting https://github.com/joltup/rn-fetch-blob/pull/736
File uris with space and other special characters are not correctly normalized. The fix is to removing 3 lines of code on `normalizePath()` because the correct normalization code already exists in `PathResolver.getRealPathFromURI()`.
Example input: `file:///storage/emulated/0/Foo%20Bar`
Correct output: `/storage/emulated/0/Foo Bar`.
Current (wrong) output: `/storage/emulated/0/Foo%20Bar`.
PS: Is it possible for you to take a look at other PRs in https://github.com/joltup/rn-fetch-blob/pull/736 as well? I know that's a lot to ask, so I get it if you say no :)

Fix normalizing file:// paths with special characters

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java

Fixes https://github.com/RonRadtke/react-native-blob-util/issues/84
@RonRadtke

Only throw error if dir does not exist after attempting to create

---

index.d.ts

As per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56758.
Source: 
- Android: https://github.com/RonRadtke/react-native-blob-util/blob/06f8c707e56331e587da0b4b65aebac9411265d0/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java#L1032
- iOS: https://github.com/RonRadtke/react-native-blob-util/blob/06f8c707e56331e587da0b4b65aebac9411265d0/ios/ReactNativeBlobUtilFS.m#L919
I suggest merging this PR once the one on DefinitelyTyped gets approved and merged

fixes FS.df callback return type

---

ios/ReactNativeBlobUtil/ReactNativeBlobUtil.m

Simple typo fix for `envionment` to `environment`

Fix "envionment" typo

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilConfig.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilUtils.java

Fixes https://github.com/joltup/rn-fetch-blob/issues/573 and probably some other issues not discovered yet.
See https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#ROOT

Use root locale for string operations

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java

for example
```js
import { launchImageLibrary } from "react-native-image-picker";
import ReactNativeBlobUtil from "react-native-blob-util";
launchImageLibrary({
mediaType: "mixed",
quality: 0.6,
})
.then((d) => d.assets)
.then((files) => {
console.log("文件路径：", files[0].uri);
return ReactNativeBlobUtil.fs.hash(files[0].uri, "sha256");
})
.then((fileHash) => {
console.log("hash sha256");
console.log(fileHash);
})
.catch((e) => {
console.log(e);
console.log("??");
});
```
previous log
```
文件路径： file:///data/user/0/com.pitayacreate.dev/cache/rn_image_picker_lib_temp_809478c6-a6b9-4bf4-b07a-620f9db1603b.jpg
[Error: No such file 'file:///data/user/0/com.pitayacreate.dev/cache/rn_image_picker_lib_temp_809478c6-a6b9-4bf4-b07a-620f9db1603b.jpg']
??
```
current log
```
文件路径： …
```

fix: 🐛 fs.xxx normalizePath

---

README.md
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilConfig.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFileTransformer.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilMediaCollection.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
fs.js
index.d.ts
ios/ReactNativeBlobUtil.xcodeproj/project.pbxproj
ios/ReactNativeBlobUtil/ReactNativeBlobUtil.m
ios/ReactNativeBlobUtilConst.h
ios/ReactNativeBlobUtilConst.m
ios/ReactNativeBlobUtilFS.h
ios/ReactNativeBlobUtilFS.m
ios/ReactNativeBlobUtilFileTransformer.h
ios/ReactNativeBlobUtilFileTransformer.m
ios/ReactNativeBlobUtilReqBuilder.m
ios/ReactNativeBlobUtilRequest.m
mediacollection.js
types.js

This change adds a concept of an optional "transformer" that allows preprocessing before writing and after reading bytes from storage via this library. 
The transformer can be set natively. The transformers can be triggered when writing to file, reading from file, writing to media file (on android), and writing the bytes of a response from a RNBU request. 
To give an example of how this might be used, in our instance of the app, the transformer is used to encrypt/decrypt content to make sure everything written to disk is encrypted. The intent with the transformer is to be as generic as possible to allow any type of byte manipulation that should be done in the various scenarios that's addressed. 
I updated the readme with documentations around this new functionality.

Adding File Transforms

---

android/src/main/java/com/ReactNativeBlobUtil/Response/ReactNativeBlobUtilFileResp.java

This fixes a progress reporting problem for Android only on files > 2.14 GB. This is not a super clean fix but it does help with my very specific use case :)

Fix content length to be capped at Integer.MAX_VALUE for downloads

---

fs.js

The fs.js `appendFile()` call to `ReactNativeBlobUtil.writeFile()` was setting `transform` to `true` and missing out the required `append` boolean value. As a result of this uploads were sometimes failing.
This changes the call to be `transform: false` and `append: true`.
More info here: https://github.com/RonRadtke/react-native-blob-util/issues/131

append file - add in missing parameter

---

polyfill/Fetch.js

Fixes the outstanding error in the joltup repo:
https://github.com/joltup/rn-fetch-blob/issues/687
This commit is pretty much just copypasta from @nadav2051 but applied to this new fork.
The assigned `task` variable is not available on the cancel method. This
moves the assignment outside the promise scope and allows it to be
correctly called.

🐛 Fix Task Scoping for Fetch Cancellation

---

index.d.ts

The type declaration did not match the implementation.

Fix type declaration for `close()` in interface `ReactNativeBlobUtilWriteStream`

---

android/src/main/AndroidManifest.xml

Recently realized this permission got added to my project after pulling in this as a dependency, which was surprising since I saw the alert on F-Droid.  This seems like a permission that should be added by the app developer if needed, not something intrinsically required/added by this library.

Remove CHECK_LICENSE permission

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java

After some more testing with the new progress reports from the Android Download Manager introduced in #143, I discovered that when multiple downloads were running at the same time, the progress amounts were getting mixed up between them.  Turns out the `query` being passed to the `DownloadManager` was not filtering by anything, so it was just hooking into all progress events there.  This change adds a filter by Id to the query to fix that.

Filter progress reports from DownloadManager by id

---

index.js

While transpiling with typescript this error will occur:
```
Error while parsing /Users/yourusername/projectpath/node_modules/react-native-blob-util/index.js
Line 58, column 0: Declaration or statement expected.
```
This is because the export must be named. It doesn't look like the export is used directly and TypeScript definitions aren't showing it either but it should be correct code to avoid blocking compilation.

Fixed export error, use named export

---

package-lock.json
package.json

Fixes CVE-2022-3517 by upgrading `glob` to include the upgrade to `minimatch` version greater than `3.0.4`.
Details: https://www.mend.io/vulnerability-database/CVE-2022-3517
Additional notes: I had to run `npm install --force` in order to update the lock file

fix CVE-2022-3517

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
android/src/main/java/com/ReactNativeBlobUtil/Utils/MimeType.java

We observed that some Android phones were crashing when executing `ReactNativeBlobUtil.MediaCollection.copyToMediaStore`.
The crash log was showing
`Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference.`
Unfortunately, none of the devices I have were crashing in this manner, and trying to debug on the few phones that the crash was observed on was impossible for us.
In this push, I am just adding a null check in all the places that perform `.isEmpty()` check. I already tested the implementation and indeed, one of these `.isEmpty()` checks was responsible for the crash.
Just in case if this will be of any help, one of the phones that were crashing is a Samsung Galaxy S8 running Android 8.

 'boolean java.lang.String.isEmpty()' on a null object reference on certain Android phones.

---

README.md

fix typo `MedaiaStore` > `Media Store`

docs: media store typo

---

CONTRIBUTING.md

Seems like this is just an example of the "rename everything" commit renaming a little more than it should. It does not seem to be a repo on https://github.com/RonRadtke/react-native-blob-util-dev either.

Fix link in CONTRIBUTING.md to dev project

---

index.web.js
package.json

e.g. when `npm run build-web` in https://github.com/flyskywhy/PixelShapeRN/tree/v1.1.23

fix: with react-native-web product build will `export 'URIUtil' (reexported as 'URIUtil') was not found`

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java

Submitting this as a potential fix for #214

Null check HashMap's get result in ReactNativeBlobUtilReq instead of checking for key first, to prevent potential async issues

---

polyfill/Fetch.js

headers['content-type'] is required because in `ReactNativeBlobUtilReq.java` content type is picked from lower case version

Fix support of FormData in Fetch polyfill on android

---

ios/ReactNativeBlobUtil/ReactNativeBlobUtil.mm

After upgrading the package to the newest version and running it with new arch enabled, there appeared the problems solved by the commit, being wrong import and method names not being the ones needed by the spec.

fix: change method names and import to proper one

---

class/ReactNativeBlobUtilCancelError.js
class/ReactNativeBlobUtilCanceledFetchError.js
fetch.js
index.d.ts
index.js
package.json

I need to have a different code path for cancellation than for normal errors. This pr adds support for properly scoping using a custom error instance:
```
.catch(error => {
const hasBeenCanceled = error instanceof ReactNativeBlobUtil.CanceledFetchError
```
Since the cancel function rejects the promise, I believe it is better to use a custom error like this to allow people to filter it easily, without resorting to error string comparison.

Add Custom Error for cancel task reject

---

windows/ReactNativeBlobUtil/ReactNativeBlobUtil.vcxproj

In VS2022 the build is defaulting to the 2017 build tools, it should default to 2019 build tools

Support Visual Studio 2022

---

README.md

The issue is, that an image URL usually does not accept 'application/octet-stream'. It is also incorrect to use JSON.stringify(dat) as a body parameter as dat is not defined, leading to issue #228

Fix CopyToMediaStore documentation

---

ios/ReactNativeBlobUtil/ReactNativeBlobUtil.h
react-native-blob-util.podspec

This PR fixes use_framework! for RN 0.72.1.
Please check it out. The path works on my PC - but errors if I don't change it.

Fix for RN 0.72.1

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilMediaCollection.java

On Android, copying files to a media store (`copyToMediaStore`) with the same name more than 32 times will crash the app. I'm not sure if the number is vary depends on the device, but on the 33rd time, the app crashed.
The error itself comes from this line of code.
https://github.com/RonRadtke/react-native-blob-util/blob/10401743630359a88ac1c551e948091c09615100/android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilMediaCollection.java#L98-L99
This PR wraps it with a `try-catch`. Now, a promise rejection warning will show instead of an error. It would be the developer's responsibility to handle the rejection.

Android - Fix failed to build unique file crash

---

ios/ReactNativeBlobUtilProgress.h

When building, we get the following warnings regarding the properties of `ReactNativeBlobUtilProgress`:
Autosynthesized property 'count' will use synthesized instance variable '_count', not existing instance variable 'count'
Autosynthesized property 'enable' will use synthesized instance variable '_enable', not existing instance variable 'enable'
Autosynthesized property 'interval' will use synthesized instance variable '_interval', not existing instance variable 'interval'
Autosynthesized property 'type' will use synthesized instance variable '_type', not existing instance variable 'type'
As all access is via these synthesized properties, the declared instance variables can be removed.

refactor(ios): re-align some autosynthesized properties

---

ios/ReactNativeBlobUtilFS.mm

Try Catch blocks catch exceptions, update call from NSError to NSException

Fix runtime crasher on Xcode 15

---

windows/ReactNativeBlobUtil/ReactNativeBlobUtil.cpp
windows/ReactNativeBlobUtil/ReactNativeBlobUtil.h

Method `addListener` and `removeListeners` were missing for windows implementation.

add missing listener methods for windows

---

android/src/newarch/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java
codegenSpecs/NativeBlobUtils.js

Methods `addListener` and `removeListeners` were missing from the codegen spec. Without them, events emitted from native code do not get sent to JS, and warnings are logged complaining about the missing methods.
Fixes: https://github.com/RonRadtke/react-native-blob-util/issues/283
Possibly also fixes:
https://github.com/RonRadtke/react-native-blob-util/issues/274
https://github.com/RonRadtke/react-native-blob-util/issues/292

add missing listener methods (new architecture)

---

mediacollection.js

`types` is within this project and should use [relative import](https://www.typescriptlang.org/docs/handbook/module-resolution.html#relative-vs-non-relative-module-imports).

Fix import declaration of `mediacollection.js`

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java

There is no need to call `getAssets().openFd` to get the file length, It is also causing strange error such as `This file can not be opened as a file descriptor; it is probably compressed` when loading a file from assets on android.

fix: reading file from assets

---

android/build.gradle

Alternatively the package names could be changed in the java files to match the current namespace.
Fixes #315

Fix for missing symbol BuildConfig

---

ios/ReactNativeBlobUtil/ReactNativeBlobUtil.mm

[stringByAddingPercentEscapesUsingEncoding:](https://developer.apple.com/documentation/foundation/nsstring/1415058-stringbyaddingpercentescapesusin) was deprecated in iOS 9.
Using the recommended replacement instead.

Fix deprecated iOS API stringByAddingPercentEscapesUsingEncoding:

---

ios/PrivacyInfo.xcprivacy
ios/ReactNativeBlobUtil.xcodeproj/project.pbxproj
react-native-blob-util.podspec

Adds a privacy manifest to comply with apples new requirements for apps and sdks:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
Attempts to solve: https://github.com/RonRadtke/react-native-blob-util/issues/342
Please let me know if any changes are needed or there is any particular way I should test this!
Tested by linking the package in our repo and generating privacy report, didn't generate errors. 
@RonRadtke

chore: first pass at adding a privacy manifest

---

.npmignore

TITC, the redundant `android/proguard-rules.pro` was excluded from the build output.

Remove android proguard rules file from build output

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilStream.java

We encountered exceptions trying to copy from `content://` URI on Android. This happens as soon as the file type isn't one of the few types explictly supported by `ReactNativeBlobUtilUtils.normalizePath`. Trying to extend the supported file types looked like a dead-end: when picking a PDF document from the `Files` app using `react-native-document-picker` for example, we get a `content://` URI which can't be accessed as a regular file as far as I can tell.
So, while `ReactNativeBlobUtilUtils.normalizePath` is definitely useful for destination files, trying to use it too much for source path is problematic.
In this pull-request, I am using [Android ContentResolver.openInputStream()](https://developer.android.com/reference/android/content/ContentResolver#openInputStream(android.net.Uri)) to …

Use content resolver for content uri on android

---

react-native-blob-util.podspec

this ensures that the version of the JS and native iOS code matches.

use version as tag for podspec

---

ios/ReactNativeBlobUtilFS.mm

The hasing functions on android iterate over the files in 1MB chunks when hashing them.  The iOS was using this api, which reads the entire file into memory at once:
```
NSData *content = [[NSFileManager defaultManager] contentsAtPath:path];
```
For large files, this was causing allocations on iOS to fail or causing out of memory issues.  This change reads the files in 1MB chunks on iOS to avoid this situation.

Fix out of memory issues hashing large files on iOS

---

ios/ReactNativeBlobUtilRequest.h
ios/ReactNativeBlobUtilRequest.mm

Set IOSBackgroundTask: true then you can download files in background.
Tested for:
- POST and GET requests.
- Single download and parallel(multiple) downloads.
- Check overwrite and fileCache property works fine.

Provided download background support to ios devices

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilFS.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilImpl.java
android/src/newarch/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java
android/src/oldarch/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java

I am not a Java developer, but we were experiencing `integer overflow` issues while working with binary files. The issue was in the `slice` function. `Start` and `end` values were declared as `int` instead of `long`. Please review the code as there could be an unnecessary cast or something missed.

Fixed integer overflow issue in slice function for android

---

ios/ReactNativeBlobUtil/ReactNativeBlobUtil.mm

In my use of `react-native-blob-util` I was reading files with the ascii encoding. When reading I would receive a `unrecognized selector sent to instance` RCTFatal error. The file read was still successful as the ascii encoding resolve function was still run correctly. The issue was the error was thrown when the UTF8 else case was also run. 
I figure each file read only one encoding resolve function should be run dependant on the encoding passed in by the user. The change to an if/else if/else should ensure only one encoder function runs compared to the previous if/if/else.

Ensuring ascii file reads do not fall through to else case for UTF-8 reading

---

index.d.ts

I have been using the `fs.slice` method for almost a year now in my app. and the slice method in the `FS` interface was returning `Promise<void>`, which created a small typing issue in the code. This PR changes it from `Promise<void>` to `Promise<string>`. In all my testing, this method never returned `void`, and because JS loads the sliced file to memory, I don't think it will ever return `void` or any other type other than string. That said, it would be best to test a scenario where the device doesn't have required storage to be able to save the slice in a different directory. In that case, it might break. If I can, I'll test it and update this PR. If anyone else wants to try, let me know. 

Changed slice  method type 

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilPackage.java

TurboReactPackage and the deprecated ReactModuleInfo constructor will be removed from a future release. These classes are already present in recent React Native releases, so this makes react-native-blob-util compatible with future RN releases.

Remove deprecated API's from react-native-blob-util

---

android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java

- 注释掉了 ReactNativeBlobUtilReq.java 中的几个 RNLog.w() 调用
- 这些日志输出主要用于调试，现在已不再需要

refactor(android): 移除不必要的日志输出

---

android/src/main/java/com/ReactNativeBlobUtil/Response/ReactNativeBlobUtilFileResp.java

Issue #407 
When downloading files larger then 2GB in progress we were getting total size as Int max and it is due to a condition to fix an bug in OKio.
There was a condition added to fix issue with OKio where body content length size grater then int.
this issue seems fixed in current versions of Okio so we removed that condition.

Fix download issue with file size 2GB+
